name: delalochu
description: A new Flutter project.
version: 1.0.6+13
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  google_sign_in: ^5.0.4
  image_picker: 1.0.2
  image: 4.0.17
  outline_gradient_button: ^2.0.0+1
  universal_platform: 1.0.0+1
  flutter_inappwebview: ^5.4.3+7
  dotted_border: 2.0.0+3
  intl: ^0.18.0
  http: ^1.1.0
  # location: 5.0.3
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  intl_phone_field: ^3.2.0
  url_launcher: ^6.2.4
  pull_to_refresh: ^2.0.0
  package_info_plus: ^4.2.0
  upgrader: ^8.4.0
  google_maps_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterBlack.ttf
          weight: 900
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
